version: '3.7'

services:
  lagrange:
    image: ghcr.io/konatadev/lagrange.onebot:edge
    container_name: lagrange
    restart: unless-stopped
    ports:
    - 8080:8080
    volumes:
    - ./lagrange:/app/data
    environment:
    - UID=1000
    - GID=1000
  meme-generator:
    image: meetwq/meme-generator:latest
    container_name: meme-generator
    restart: unless-stopped
    ports:
    - 23333:2233

networks:
  default:
    name: net0
    external: true
