# Usage:
#     docker-compose up -d

version: '3.7'

services:
  go-cqhttp:
    image: ghcr.io/mrs4s/go-cqhttp:dev-old
    depends_on:
    - qsign
    volumes:
    - ./go-cqhttp:/data
    - ./koishi:/koishi:ro
    ports:
    - 8080:8080
    restart: always
  qsign:
    image: xzhouqd/qsign:core-1.1.7
    environment:
    - BASE_PATH=/srv/qsign/qsign/txlib/8.9.63
    restart: always
